### ISSUE TITLE
DIA

### ISSUE THREAD

**Issue by mchiapello** [medbioinf/pia#117]
Does PIA work also with DIA data? 

Is there a way to integrate the [OpenSwath pipeline](http://www.openswath.org/en/latest/index.html#) with PIA?

**Comment by julianu** [comment]
Hej Marco,
Actually, PIA should work with DIA data as well, as long as you only want to look at the identification values. I never tried it with OpenSwath, though trying it out is on my agenda.
Does OpenSwath work with idXML files for identification, or mzIdentML, like OpenMS? If yes, could you maybe provide some files for a test run? If not, what file format is used by OpenSwath for identifications?

**Comment by mchiapello** [comment]
Hi Julian, 
thank you for the quick reply. 

I just started working with DIA and I have not real experience with OpenSwath, but I believe it can not work with idXML or mzIdentML files, like OpenMS. Nevertheless I will investigate.

OpenSwath uses for identification mzML files and produces 2 outputs:
- Extracted chromatograms (as mzML)
- Identified peaks (as tsv)

Hope this help.

**Comment by mchiapello** [comment]
> PIA should work with DIA data as well, as long as you only want to look at the identification values
This means PIA is not doing any quantification, right?

**Comment by julianu** [comment]
Right, PIA can only create the protein grouping on the given peptide identifications. This information can be passed on to protein quantifiers, though. It works currently nice together with OpenMS, hence the question above.

Hm... if there is only a TSV probably some implementation work is needed to get it to work with openSWATH. As mentioned, I would like to give it a try, but can currently not promise, when I will have time for this.
If you find out, that also in OpenSWATH mzIdentML or idXML are used, give me a note.

But regarding the identification, before creating the library, you should be able to use PIA for the FDR filtering and combining of PSMs from different search engines. Again, only if OpenSWATH uses mzid or idXML for the import of library generation, though.

**Comment by mchiapello** [comment]
> Right, PIA can only create the protein grouping on the given peptide identifications. This information can be passed on to protein quantifiers, though. It works currently nice together with OpenMS

At which "protein quantifiers" do you refer to? 

> If you find out, that also in OpenSWATH mzIdentML or idXML are used, give me a note.

I doubled check with my collegues and they confirmed that OpenSWATH does not use mzIdentML or idXML.

**Comment by julianu** [comment]
I am referring to the OpenMS tool/module ProteinQuantifier (http://ftp.mi.fu-berlin.de/pub/OpenMS/release-documentation/html/TOPP_ProteinQuantifier.html). This takes the grouping of PIA (peptides assigned to protein groups) and uses it for the calculation of protein quantifications.

**Comment by mchiapello** [comment]
I enquired the openswath's developer, here the replay:
> As input, OpenSWATH requires spectral libraries and it supports HUPO-PSI
TraML, which can be generated from pepXML/mzIdentML/idXML via SpectraST.

Is it what you were referring to?

Il ven 10 ago 2018, 17:36 Julian Uszkoreit <notifications@github.com> ha
scritto:

**Comment by julianu** [comment]
Yes, this is what I meant, that you can use PIA for the merging of search engine results and calculating the FDR. After an mzIdentML export, you might be able to format this into TraML (which I have not testet, though).

**Comment by mchiapello** [comment]
The plan is: 
1. Use PIA on DDA searches
1. Format the result file into TraML
1. Use OpenSwath to do the DIA analysis

Do you think we need one more step of protein inference?

**Comment by julianu** [comment]
You obviously need any protein inference, if you want to go from the identified/quantified peptides of your DIA experiment to the corresponding proteins.
But as said before, I don't know the formats  OpenSWATH is using there and therefore whether PIA can process them or help you with this (yet).
