### ISSUE TITLE
PSM ms_run[] get repeated in mztab export. 

### ISSUE THREAD

**Issue by ypriverol** [medbioinf/pia#133]
For some reason PSM ms_run[] get repeated in mztab export. Here and exmaple: 

PSM     FGIAAK  1       P21796  0       databaseName    null    [MS, MS:1002387, PIA, 1.3.10]|[PSI-MS, MS:1001476, X!Tandem, X! Tandem Alanine (2017.2.1.4)]|[PSI-MS, MS:1002048, MS-GF+, Release (v2017.07.21)]        0.003638683087973093    0.0075  20.0    0.004483837330552659    115.0   1.7413855E-8    0.34254366      null    1729.1622       2       303.68479405403644      303.683456328125        ms_run[1]:index=1433|ms_run[1]:index=1433|ms_run[1]:index=1433|ms_run[2]:index=1433|ms_run[2]:index=1433|ms_run[2]:index=1433   R       Y       219     224     0       0       1

**Comment by ypriverol** [comment]
Error found and fixed, PR pending. One questions for @julianu . 

In the mztab export when you export one PSM (that is a PSMSet) that contains a list psms. We use to export all the ms_runs even if the scores are different. IS that correct @julianu see line: 

https://github.com/mpc-bioinformatics/pia/blob/878f40382e2f24fab1a375ccaa0cf6504ee337d5/src/main/java/de/mpc/pia/modeller/exporter/MzTabExporter.java#L1082

**Comment by ypriverol** [comment]
Yes. Still you should read my comment before.

**Comment by julianu** [comment]
When exporting PSMSets, all scores of the PSMs of the set will be exported, yes.
When using only one search engine and combining the results of multiple ms_runs, no sets need to be created (and actually should, if everything goes well, have just one PSM if sets were created.)
