### ISSUE TITLE
PIA error in KNIME

### ISSUE THREAD

**Issue by algalcms** [medbioinf/pia#186]
Hi, I am trying to use PIA in Knime for analysis of LC/MS data, but during start of the PIA the node with ID suffix 570 (PIA compiler) crashes, and I receive following error log:
ERROR 01-PIA_first_analysis 0          Unable to load node with ID suffix 570 into workflow, skipping it: javax/xml/bind/JAXBException
ERROR LoadWorkflowRunnable            Errors during load: Status: Error: 01-PIA_first_analysis 0 loaded with errors
ERROR LoadWorkflowRunnable              Status: Error: 01-PIA_first_analysis 0
ERROR LoadWorkflowRunnable                Status: Error: Unable to load node with ID suffix 570 into workflow, skipping it: javax/xml/bind/JAXBException

How should I solve this problem? All necessary items are installed. PC with Win10 x64.
Thank you!

**Comment by julianu** [comment]
Hej @algalcms ,
Could you provide the version of KNIME and the PIA plugin you are using?

**Comment by algalcms** [comment]
Hi,
I am using Knime 4.5, PIA version 1.3.13 and OpenMS 2.7 .

**Comment by julianu** [comment]
Could you please try to upgrade to the newest version of the PIA plugin? There was a major internal change for KNIME 4.4 which took place some versions later than 1.3.13

**Comment by algalcms** [comment]
Hi, thank you so much to help me.
I tried to update the PIA, but I got error again. See the attached pix. When I want to add PIA compiler manually directly from node repository, I also receive an error. I do not know, where I have to uninstall the PIA first, Im not able to find uninstall option.

![pia1](https://user-images.githubusercontent.com/98087275/150342223-6a961817-19cf-48fb-9846-30b4a310ecd4.jpg)
![pia2](https://user-images.githubusercontent.com/98087275/150342234-8b118dd7-542b-47a6-86e2-03b90b59e8b9.jpg)
![pia3](https://user-images.githubusercontent.com/98087275/150342244-44981120-b54d-49c0-b189-5dee811dc200.jpg)

**Comment by julianu** [comment]
Hm, this looks weird. The error rather indicates, that there is the old version still used, which breaks with KNIME >4.3 though.
Could you try to cleanly uninstall the current PIA version first, restart KNIME and install the newest version? Maybe this does the trick.

**Comment by algalcms** [comment]
Hi, 
After clean installation I still have the same problem. It seems, that there is problem with PIA compiler. Other components were loaded successfully.

**Comment by julianu** [comment]
I would expect this error, if for some reason a wrong Java version was used. But this should not be possible with KNIME.

Last week, new versions of PIA were released. Could you please try again to upgrade and, if this does not help, try a clean installation of KNIME? You could just download the zipfile version and unzip it anywhere, to not interfere with your current KNIME version.

**Comment by algalcms** [comment]
Hi,
thank you for your help. Ill try to do this things during next week, now I am busy with evaluation of LC/MS data by another pathway. Ill let you know about the results.

**Comment by julianu** [comment]
(closed due to inactivity and KNIME updates)
